#ifndef ROOFITHEAD_H
#define ROOFITHEAD_H
/// RooFit headers
#include <RooRealVar.h>
#include <RooDataSet.h>
#include <RooGaussian.h>
#include <RooPlot.h>
#include <RooHistPdf.h>
#include <RooHistFunc.h>
#include <RooExponential.h>
#include <RooPolynomial.h>
#include <RooPolyVar.h>
#include <RooAddPdf.h>
#include <RooAbsData.h>
#include <RooAbsRealLValue.h>
#include <RooAbsPdf.h>
#include <RooMinuit.h>
#include <RooCategory.h>
#include <RooArgSet.h>
#include <RooDataHist.h>
#include <RooNLLVar.h>
#include <RooSimultaneous.h>
#include <RooExponential.h>
#include <RooGlobalFunc.h>
#include <RooCBShape.h>
#include <RooFormula.h>
#include <RooRandom.h>
#include <RooFitResult.h>
#include <RooProdPdf.h>
#include <RooProfileLL.h>
#include <RooLognormal.h>
#include <RooPoisson.h>
#include <RooProduct.h>
#include <RooAddition.h>
#include <RooBifurGauss.h>
#include <Roo1DTable.h>
#include <RooBernstein.h>
#include <RooArgList.h>
#include <RooConstVar.h>
#include <RooExtendPdf.h>
#include <RooGenericPdf.h>
#include <RooChebychev.h>
#include <RooLognormal.h>
#include <RooNovosibirsk.h>
#include <RooLandau.h>
#include <RooWorkspace.h>
#include <RooRealSumPdf.h>
#include <RooNumIntConfig.h>
#endif
